services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inkomi-api
    restart: unless-stopped
    volumes:
      - ./resources:/app/resources
      - ./firebase.json:/app/firebase.json
    ports:
      - "3000:3000"
